changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - app/dependabot
  categories:
    - title: New features
      labels:
        - enhancement
        - new feature
    - title: Fixes
      labels:
        - bug
    - title: Other Changes
      labels:
        - "*"